// All meal data for Khane mein kya?
// Kept separate from UI so designs can iterate without touching the menu.

// Master list of vegetables we'll show as chips.
// Lead with specialty veggies — the ones you'd actually plan around.
// Common staples (onion, tomato, etc.) are assumed always at home but
// still listed under "show more" in case the user wants to nudge.
const VEG_OPTIONS = [
  "spinach","cauliflower","bell pepper","methi","bhindi","mushroom",
  "broccoli","eggplant","karela","drumstick","tinda","zucchini",
  "gawar","ridge gourd","pumpkin","beetroot","radish","gongura","arbi",
  "_more_",
  "potato","peas","carrot","cabbage","lauki","sweet potato",
  "sweetcorn","cucumber","tomato","onion","garlic","beans"
];

const GRAIN_OPTIONS = [
  "rice","wheat","rava","poha","oats","millets","ragi","daliya",
  "_more_",
  "quinoa","jowar","vermicelli","sabudhana","chia","pasta","noodles","bread","tortilla"
];

const PULSE_OPTIONS = [
  "moong dal","toor dal","chana dal","urad","masoor dal",
  "rajma","chickpea","kala channa","lobia",
  "sprouts","besan","paneer","tofu","peanut"
];

/* Each item:
     src      - optional source attribution ("chefandherkitchen", "hebbarskitchen")
                — omitted = original menu from the family's home spreadsheet
     n        - display name
     slot     - breakfast | tiffin | lunch | snack | dinner
     cuisine  - Indian | Asian | Mexican | Italian | Continental
     dairy    - none | light | heavy
     protein  - low | med | high
     soak     - true if needs overnight soak
     veg      - vegetables used
     grain    - grains used
     pulse    - pulses / proteins used
*/
const MENU = [
  // ---------- BREAKFAST ----------
  { n:"Rava Upma", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion","peas","carrot"], grain:["rava"], pulse:[] },
  { n:"Millets Upma", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["onion","peas","carrot"], grain:["millets"], pulse:[] },
  { n:"Poha - Brown", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion","peas"], grain:["poha"], pulse:[] },
  { n:"Poha - Green", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion"], grain:["poha"], pulse:[] },
  { n:"Oats Pongal", slot:"breakfast", cuisine:"Indian", dairy:"light", protein:"med",
    veg:[], grain:["oats"], pulse:["moong dal"] },
  { n:"Oats Chilla", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["onion","tomato"], grain:["oats"], pulse:[] },
  { n:"Moong Dal Chilla", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion"], grain:[], pulse:["moong dal"] },
  { n:"Besan Chilla", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:[], pulse:["besan"] },
  { n:"Ragi Upma", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["onion","peas"], grain:["ragi"], pulse:[] },
  { n:"Ragi Dosa", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:[], grain:["ragi","rice"], pulse:["urad"], soak:true },
  { n:"Ragi Porridge", slot:"breakfast", cuisine:"Indian", dairy:"heavy", protein:"med",
    veg:[], grain:["ragi"], pulse:[] },
  { n:"Jowar Porridge", slot:"breakfast", cuisine:"Indian", dairy:"heavy", protein:"med",
    veg:[], grain:["jowar"], pulse:[] },
  { n:"Daliya Khichdi", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["onion","peas","carrot"], grain:["daliya"], pulse:["moong dal"] },
  { n:"Oats Idli", slot:"breakfast", cuisine:"Indian", dairy:"light", protein:"med",
    veg:[], grain:["oats","rava"], pulse:[] },
  { n:"Vermicelli Upma", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion","peas"], grain:["vermicelli"], pulse:[] },
  { n:"Dhokla - White / Katta", slot:"breakfast", cuisine:"Indian", dairy:"light", protein:"med",
    veg:[], grain:["rice"], pulse:["urad"], soak:true },
  { n:"Dhokla - Kaman", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:[], grain:[], pulse:["besan"] },
  { n:"Paratha - Aloo", slot:"breakfast", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["potato"], grain:["wheat"], pulse:[] },
  { n:"Paratha - Methi", slot:"breakfast", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["methi"], grain:["wheat"], pulse:[] },
  { n:"Paratha - Paneer", slot:"breakfast", cuisine:"Indian", dairy:"heavy", protein:"high",
    veg:[], grain:["wheat"], pulse:["paneer"] },
  { n:"Tikki - Sabudhana", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato"], grain:["sabudhana"], pulse:[], soak:true },
  { n:"Tikki - Aloo", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato"], grain:[], pulse:[] },
  { n:"Tikki - Sweet Potato / Makhana", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["sweet potato"], grain:[], pulse:[] },
  { n:"Tikki - Harabhara", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["spinach","peas"], grain:[], pulse:[] },
  { n:"Paneer Burjhi", slot:"breakfast", cuisine:"Indian", dairy:"heavy", protein:"high",
    veg:["onion","tomato"], grain:[], pulse:["paneer"] },
  { n:"Sprouts", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:[], pulse:["sprouts"], soak:true },
  { n:"Cereals", slot:"breakfast", cuisine:"Continental", dairy:"heavy", protein:"med",
    veg:[], grain:["oats","wheat"], pulse:[] },
  { n:"Oat Flour Pancakes", slot:"breakfast", cuisine:"Continental", dairy:"light", protein:"low",
    veg:[], grain:["oats"], pulse:[] },
  { n:"Smoothie Bowl", slot:"breakfast", cuisine:"Continental", dairy:"heavy", protein:"med",
    veg:[], grain:["oats"], pulse:[] },
  { n:"Quinoa Upma", slot:"breakfast", cuisine:"Continental", dairy:"none", protein:"high",
    veg:["onion","peas","carrot"], grain:["quinoa"], pulse:[] },
  { n:"Chia Pudding", slot:"breakfast", cuisine:"Continental", dairy:"heavy", protein:"med",
    veg:[], grain:["chia"], pulse:[], soak:true },
  { n:"Fruit Salad Bowl", slot:"breakfast", cuisine:"Continental", dairy:"none", protein:"low",
    veg:[], grain:[], pulse:[] },
  { n:"Oats and Chia (with Urad)", slot:"breakfast", cuisine:"Continental", dairy:"light", protein:"med",
    veg:[], grain:["oats","chia"], pulse:["urad"], soak:true },
  { n:"Sandwich - Mumbai", slot:"breakfast", cuisine:"Continental", dairy:"light", protein:"low",
    veg:["potato","cucumber","tomato"], grain:["bread"], pulse:[] },
  { n:"Sandwich - PBJ", slot:"breakfast", cuisine:"Continental", dairy:"none", protein:"med",
    veg:[], grain:["bread"], pulse:["peanut"] },
  // -- South Indian additions --
  { n:"Adai", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion"], grain:["rice"], pulse:["chana dal","toor dal","urad"], soak:true },
  { n:"Pesarattu", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion"], grain:["rice"], pulse:["moong dal"], soak:true },
  { n:"Akki Roti", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion","carrot"], grain:["rice"], pulse:[] },
  { n:"Sevai / Idiyappam", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"low",
    veg:[], grain:["rice"], pulse:[] },
  // -- Kid-friendly Continental --
  { n:"Cheerios + Yogurt", slot:"breakfast", cuisine:"Continental", dairy:"heavy", protein:"med",
    veg:[], grain:["oats"], pulse:[] },

  // ---------- TIFFIN BOX ----------
  { n:"Thepla", slot:"tiffin", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["methi"], grain:["wheat"], pulse:[] },
  { n:"Moong Dal Chilla Wrap", slot:"tiffin", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion"], grain:[], pulse:["moong dal"] },
  { n:"Besan Chilla Roll", slot:"tiffin", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:[], pulse:["besan"] },
  { n:"Roasted Makhana", slot:"tiffin", cuisine:"Indian", dairy:"none", protein:"med",
    veg:[], grain:[], pulse:[] },
  { n:"Veggie Rice Balls", slot:"tiffin", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["carrot","peas"], grain:["rice"], pulse:[] },
  { n:"Steamed Momos (Veg)", slot:"tiffin", cuisine:"Asian", dairy:"none", protein:"low",
    veg:["cabbage","carrot"], grain:["wheat"], pulse:[] },
  { n:"Broccoli Pizza", slot:"tiffin", cuisine:"Italian", dairy:"heavy", protein:"med",
    veg:["broccoli"], grain:["wheat"], pulse:["paneer"] },
  { n:"Hummus (Plain)", slot:"tiffin", cuisine:"Continental", dairy:"none", protein:"med",
    veg:[], grain:[], pulse:["chickpea"], soak:true },
  { n:"PBJ Sandwich", slot:"tiffin", cuisine:"Continental", dairy:"none", protein:"med",
    veg:[], grain:["bread"], pulse:["peanut"] },
  { n:"Homemade Granola Bar (Oats+Nuts)", slot:"tiffin", cuisine:"Continental", dairy:"none", protein:"med",
    veg:[], grain:["oats"], pulse:[] },
  { n:"Fruit & Nut Mix", slot:"tiffin", cuisine:"Continental", dairy:"none", protein:"med",
    veg:[], grain:[], pulse:[] },
  { n:"Sandwich", slot:"tiffin", cuisine:"Continental", dairy:"light", protein:"low",
    veg:["cucumber","tomato"], grain:["bread"], pulse:[] },
  // -- Kid-friendly tiffin additions --
  { n:"Mini Idlis", slot:"tiffin", cuisine:"Indian", dairy:"none", protein:"med",
    veg:[], grain:["rice"], pulse:["urad"], soak:true },
  { n:"Methi Khakra", slot:"tiffin", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["methi"], grain:["wheat"], pulse:[] },
  { n:"Sabudana Khichdi", slot:"tiffin", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato"], grain:["sabudhana"], pulse:["peanut"], soak:true },
  { n:"Veggie Roll-up", slot:"tiffin", cuisine:"Continental", dairy:"none", protein:"med",
    veg:["carrot","cucumber"], grain:["wheat"], pulse:["chickpea"] },
  { n:"Lemon Rice (Tiffin)", slot:"tiffin", cuisine:"Indian", dairy:"none", protein:"low",
    veg:[], grain:["rice"], pulse:["peanut"] },
  { n:"Coconut Rice (Tiffin)", slot:"tiffin", cuisine:"Indian", dairy:"none", protein:"low",
    veg:[], grain:["rice"], pulse:[] },

  // ---------- LUNCH ----------
  { n:"Bhindi Sabzi + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["bhindi"], grain:["wheat"], pulse:[] },
  { n:"Gawar Sabzi + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["gawar"], grain:["wheat"], pulse:[] },
  { n:"Beetroot Sabzi + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["beetroot"], grain:["wheat"], pulse:[] },
  { n:"Lauki Sabzi + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["lauki"], grain:["wheat"], pulse:[] },
  { n:"Turai / Ridge Gourd Sabzi + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["ridge gourd"], grain:["wheat"], pulse:[] },
  { n:"Cabbage Sabzi + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["cabbage"], grain:["wheat"], pulse:[] },
  { n:"Palak-Dal Sabzi + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["spinach"], grain:["rice"], pulse:["toor dal"] },
  { n:"Aloo Matar + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato","peas"], grain:["wheat"], pulse:[] },
  { n:"Akka Massoor + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:["rice"], pulse:["masoor dal"] },
  { n:"Daal Rasam + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["tomato"], grain:["rice"], pulse:["toor dal"] },
  { n:"Tomato Rasam + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["tomato"], grain:["rice"], pulse:[] },
  { n:"Garlic Rasam + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["garlic"], grain:["rice"], pulse:["toor dal"] },
  { n:"Mixed Daal + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:["rice"], pulse:["toor dal","moong dal","chana dal"] },
  { n:"Palak Dal + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["spinach"], grain:["rice"], pulse:["toor dal"] },
  { n:"Chana Dal + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion"], grain:["rice"], pulse:["chana dal"] },
  { n:"Methi Dal + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["methi"], grain:["rice"], pulse:["toor dal"] },
  { n:"Moong Dal Soup + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:[], grain:["wheat"], pulse:["moong dal"] },
  { n:"Masala Khichdi", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["peas","carrot","onion"], grain:["rice"], pulse:["moong dal"] },
  { n:"Spinach Khichdi", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["spinach"], grain:["rice"], pulse:["moong dal"] },
  { n:"Dalia Khichdi", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["peas","carrot"], grain:["daliya"], pulse:["moong dal"] },
  { n:"Rajma Chawal", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:["rice"], pulse:["rajma"], soak:true },
  { n:"Lobia / Chawli + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:["rice"], pulse:["lobia"], soak:true },
  { n:"Biryani", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["carrot","peas","cauliflower","potato"], grain:["rice"], pulse:[] },
  { n:"Pulav", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["carrot","peas"], grain:["rice"], pulse:[] },
  { n:"Channa Pulao", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion"], grain:["rice"], pulse:["chickpea"], soak:true },
  { n:"Matar Paneer + Roti", slot:"lunch", cuisine:"Indian", dairy:"heavy", protein:"high",
    veg:["peas","tomato"], grain:["wheat"], pulse:["paneer"] },
  { n:"Kadhi + Rice", slot:"lunch", cuisine:"Indian", dairy:"heavy", protein:"med",
    veg:[], grain:["rice"], pulse:["besan"] },
  { n:"Stuffed Capsicum (Baked) + Roti", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["bell pepper","potato"], grain:["wheat"], pulse:[] },
  { n:"Pasta Primavera", slot:"lunch", cuisine:"Italian", dairy:"light", protein:"low",
    veg:["bell pepper","broccoli","carrot","tomato"], grain:["pasta"], pulse:[] },
  { n:"Penne Arrabbiata", slot:"lunch", cuisine:"Italian", dairy:"none", protein:"low",
    veg:["tomato"], grain:["pasta"], pulse:[] },
  { n:"Quinoa Salad Bowl", slot:"lunch", cuisine:"Continental", dairy:"none", protein:"high",
    veg:["cucumber","tomato","bell pepper"], grain:["quinoa"], pulse:[] },
  // -- Sambar varieties --
  { n:"Vegetable Sambar + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["carrot","beans","drumstick","pumpkin","tomato"], grain:["rice"], pulse:["toor dal"] },
  { n:"Drumstick Sambar + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["drumstick","tomato"], grain:["rice"], pulse:["toor dal"] },
  { n:"Muli (Radish) Sambar + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["radish","tomato"], grain:["rice"], pulse:["toor dal"] },
  // -- South Indian rice mixes & combos --
  { n:"Bisi Bele Bhath", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["carrot","peas","beans"], grain:["rice"], pulse:["toor dal"] },
  { n:"Curd Rice", slot:"lunch", cuisine:"Indian", dairy:"heavy", protein:"low",
    veg:[], grain:["rice"], pulse:[] },
  { n:"Lemon Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:[], grain:["rice"], pulse:["peanut"] },
  { n:"Coconut Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:[], grain:["rice"], pulse:[] },
  { n:"Tamarind Rice (Puliyodharai)", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:[], grain:["rice"], pulse:["peanut"] },
  { n:"Avial + Rice", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["carrot","beans","drumstick"], grain:["rice"], pulse:[] },
  // -- Poriyals (South Indian dry sabzis) --
  { n:"Beans Poriyal + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["beans"], grain:["rice"], pulse:[] },
  { n:"Cabbage Poriyal + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["cabbage"], grain:["rice"], pulse:[] },
  { n:"Carrot Poriyal + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["carrot"], grain:["rice"], pulse:[] },
  // -- North Indian sabzis --
  { n:"Methi Aloo + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["methi","potato"], grain:["wheat"], pulse:[] },
  { n:"Aloo Palak + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato","spinach"], grain:["wheat"], pulse:[] },
  { n:"Karela Sabzi + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["karela"], grain:["wheat"], pulse:[] },
  { n:"Tinda Sabzi + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["tinda"], grain:["wheat"], pulse:[] },
  { n:"Capsicum Sabzi + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["bell pepper"], grain:["wheat"], pulse:[] },

  // ---------- SNACK ----------
  { n:"Roasted Makhana", slot:"snack", cuisine:"Indian", dairy:"none", protein:"med",
    veg:[], grain:[], pulse:[] },
  { n:"Roasted Chana", slot:"snack", cuisine:"Indian", dairy:"none", protein:"high",
    veg:[], grain:[], pulse:["chickpea"] },
  { n:"Sprouts Chaat", slot:"snack", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:[], pulse:["sprouts"], soak:true },
  { n:"Fruit Chaat", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:[], grain:[], pulse:[] },
  { n:"Muhmurra", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion","tomato"], grain:[], pulse:[] },
  { n:"Bang Bang Cauliflower", slot:"snack", cuisine:"Asian", dairy:"light", protein:"low",
    veg:["cauliflower"], grain:[], pulse:[] },
  { n:"Cucumber / Carrot Sticks + Hummus", slot:"snack", cuisine:"Continental", dairy:"none", protein:"med",
    veg:["cucumber","carrot"], grain:[], pulse:["chickpea"], soak:true },
  { n:"Yogurt Parfait", slot:"snack", cuisine:"Continental", dairy:"heavy", protein:"med",
    veg:[], grain:["oats"], pulse:[] },
  { n:"Baked Shakarpara", slot:"snack", cuisine:"Indian", dairy:"light", protein:"low",
    veg:[], grain:["wheat"], pulse:[] },
  // -- Chaat & street snacks --
  { n:"Bhel Puri", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion","tomato","potato"], grain:[], pulse:[] },
  { n:"Sukha Bhel", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion","tomato"], grain:[], pulse:[] },
  { n:"Aloo Chaat", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato","onion","tomato"], grain:[], pulse:[] },
  { n:"Corn Chaat", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["sweetcorn","onion","tomato"], grain:[], pulse:[] },
  // -- Steamed / baked snacks --
  { n:"Sundal", slot:"snack", cuisine:"Indian", dairy:"none", protein:"high",
    veg:[], grain:[], pulse:["chickpea"], soak:true },
  { n:"Veg Cutlets (Baked)", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato","carrot","peas"], grain:[], pulse:[] },
  { n:"Methi Muthia (Steamed)", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["methi"], grain:["wheat"], pulse:["besan"] },
  { n:"Lauki Muthia (Steamed)", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["lauki"], grain:["wheat"], pulse:["besan"] },
  { n:"Plain Khakra", slot:"snack", cuisine:"Indian", dairy:"light", protein:"low",
    veg:[], grain:["wheat"], pulse:[] },
  { n:"Bangalore Iyengar Toast", slot:"snack", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["onion","tomato"], grain:["bread"], pulse:[] },
  // -- Continental snacks --
  { n:"Date & Nut Energy Balls", slot:"snack", cuisine:"Continental", dairy:"none", protein:"med",
    veg:[], grain:["oats"], pulse:[] },
  { n:"Roasted Mixed Nuts", slot:"snack", cuisine:"Continental", dairy:"none", protein:"med",
    veg:[], grain:[], pulse:[] },
  { n:"Bruschetta", slot:"snack", cuisine:"Italian", dairy:"light", protein:"low",
    veg:["tomato"], grain:["bread"], pulse:[] },

  // ---------- DINNER ----------
  { n:"Pav-Bhaji", slot:"dinner", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["potato","peas","cauliflower","bell pepper","tomato"], grain:["wheat"], pulse:[] },
  { n:"Missal Pav", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:["wheat"], pulse:["sprouts"], soak:true },
  { n:"Kati Roll", slot:"dinner", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["onion","bell pepper"], grain:["wheat"], pulse:["paneer"] },
  { n:"Chhole + Roti", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:["wheat"], pulse:["chickpea"], soak:true },
  { n:"Kala Channa + Rice", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:["rice"], pulse:["kala channa"], soak:true },
  { n:"Dosa", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"med",
    veg:[], grain:["rice"], pulse:["urad"], soak:true },
  { n:"Idly", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"med",
    veg:[], grain:["rice"], pulse:["urad"], soak:true },
  { n:"Rava Idly", slot:"dinner", cuisine:"Indian", dairy:"light", protein:"low",
    veg:[], grain:["rava"], pulse:[] },
  { n:"Palak Paneer + Roti", slot:"dinner", cuisine:"Indian", dairy:"heavy", protein:"high",
    veg:["spinach"], grain:["wheat"], pulse:["paneer"] },
  { n:"Palak Mushroom + Roti", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["spinach","mushroom"], grain:["wheat"], pulse:[] },
  { n:"Methi Paneer + Roti", slot:"dinner", cuisine:"Indian", dairy:"heavy", protein:"high",
    veg:["methi"], grain:["wheat"], pulse:["paneer"] },
  { n:"Mushroom Masala + Roti", slot:"dinner", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["mushroom"], grain:["wheat"], pulse:[] },
  { n:"Baingan Bharta + Roti", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["eggplant"], grain:["wheat"], pulse:[] },
  { n:"Aloo Gobi + Roti", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato","cauliflower"], grain:["wheat"], pulse:[] },
  { n:"Dal Makhani (Light) + Roti", slot:"dinner", cuisine:"Indian", dairy:"light", protein:"high",
    veg:[], grain:["wheat"], pulse:["urad","rajma"], soak:true },
  { n:"Pumpkin Curry + Roti", slot:"dinner", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["pumpkin"], grain:["wheat"], pulse:[] },
  { n:"Veg Stew + Appam/Rice", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["carrot","potato","peas"], grain:["rice"], pulse:[] },
  { n:"Stuffed Bell Peppers (Baked)", slot:"dinner", cuisine:"Continental", dairy:"light", protein:"low",
    veg:["bell pepper"], grain:["rice"], pulse:[] },
  { n:"Soup - Tomato + Toast", slot:"dinner", cuisine:"Continental", dairy:"none", protein:"low",
    veg:["tomato"], grain:["bread"], pulse:[] },
  { n:"Soup - Sweetcorn + Toast", slot:"dinner", cuisine:"Continental", dairy:"light", protein:"low",
    veg:["sweetcorn"], grain:["bread"], pulse:[] },
  { n:"Lentil Soup + Toast", slot:"dinner", cuisine:"Continental", dairy:"none", protein:"high",
    veg:["carrot","onion"], grain:["bread"], pulse:["masoor dal"] },
  { n:"Vegetable Clear Soup + Toast", slot:"dinner", cuisine:"Continental", dairy:"none", protein:"low",
    veg:["carrot","cabbage"], grain:["bread"], pulse:[] },
  { n:"Matar Paneer + Roti", slot:"dinner", cuisine:"Indian", dairy:"heavy", protein:"high",
    veg:["peas","tomato"], grain:["wheat"], pulse:["paneer"] },
  { n:"Noodles (Hakka)", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"low",
    veg:["cabbage","carrot","bell pepper"], grain:["noodles"], pulse:[] },
  { n:"Millets Noodles", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"med",
    veg:["cabbage","carrot","bell pepper"], grain:["millets","noodles"], pulse:[] },
  { n:"Thai Red Curry + Rice", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"low",
    veg:["bell pepper","broccoli","carrot"], grain:["rice"], pulse:[] },
  { n:"Thai Green Curry + Rice", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"low",
    veg:["bell pepper","broccoli","carrot"], grain:["rice"], pulse:[] },
  { n:"Chili Tofu + Rice", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"high",
    veg:["bell pepper","onion"], grain:["rice"], pulse:["tofu"] },
  { n:"Tofu Stir Fry + Rice", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"high",
    veg:["broccoli","bell pepper","carrot"], grain:["rice"], pulse:["tofu"] },
  { n:"Fried Rice w/ Gravy", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"low",
    veg:["cabbage","carrot","bell pepper"], grain:["rice"], pulse:[] },
  { n:"Millet Buddha Bowl", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"med",
    veg:["carrot","cucumber","bell pepper"], grain:["millets"], pulse:["chickpea"] },
  { n:"Soup - Manchow + Toast", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"low",
    veg:["cabbage","carrot"], grain:["noodles"], pulse:[] },
  { n:"Mexican Tacos", slot:"dinner", cuisine:"Mexican", dairy:"light", protein:"med",
    veg:["bell pepper","onion","tomato"], grain:["tortilla"], pulse:[] },
  { n:"Tacos", slot:"dinner", cuisine:"Mexican", dairy:"light", protein:"med",
    veg:["bell pepper","onion","tomato"], grain:["tortilla"], pulse:[] },
  { n:"Quesadilla", slot:"dinner", cuisine:"Mexican", dairy:"heavy", protein:"med",
    veg:["bell pepper","onion"], grain:["tortilla"], pulse:[] },
  { n:"Burrito Bowl", slot:"dinner", cuisine:"Mexican", dairy:"light", protein:"high",
    veg:["bell pepper","onion","tomato"], grain:["rice"], pulse:[] },
  { n:"Pasta", slot:"dinner", cuisine:"Italian", dairy:"light", protein:"low",
    veg:["tomato"], grain:["pasta"], pulse:[] },
  { n:"Spaghetti", slot:"dinner", cuisine:"Italian", dairy:"light", protein:"low",
    veg:["tomato"], grain:["pasta"], pulse:[] },
  { n:"Spaghetti Arrabbiata", slot:"dinner", cuisine:"Italian", dairy:"none", protein:"low",
    veg:["tomato"], grain:["pasta"], pulse:[] },
  { n:"Penne with Pesto", slot:"dinner", cuisine:"Italian", dairy:"light", protein:"low",
    veg:[], grain:["pasta"], pulse:[] },
  { n:"Mushroom Risotto", slot:"dinner", cuisine:"Italian", dairy:"heavy", protein:"med",
    veg:["mushroom"], grain:["rice"], pulse:[] },
  // -- South Indian dinner additions --
  { n:"Adai + Avial", slot:"dinner", cuisine:"Indian", dairy:"light", protein:"high",
    veg:["carrot","beans","drumstick"], grain:["rice"], pulse:["chana dal","toor dal","urad"], soak:true },
  { n:"Sambar + Rice + Poriyal", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["beans","carrot","drumstick"], grain:["rice"], pulse:["toor dal"] },
  // -- North Indian dinner additions --
  { n:"Saag Paneer + Roti", slot:"dinner", cuisine:"Indian", dairy:"heavy", protein:"high",
    veg:["spinach"], grain:["wheat"], pulse:["paneer"] },
  { n:"Vegetable Korma + Roti", slot:"dinner", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["carrot","peas","beans","cauliflower"], grain:["wheat"], pulse:[] },
  { n:"Aloo Palak + Roti", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato","spinach"], grain:["wheat"], pulse:[] },
  // -- Asian additions --
  { n:"Tofu Coconut Curry + Rice", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"high",
    veg:["bell pepper","broccoli"], grain:["rice"], pulse:["tofu"] },
  { n:"Sweet & Sour Tofu + Rice", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"high",
    veg:["bell pepper"], grain:["rice"], pulse:["tofu"] },
  { n:"Vegetable Sushi Rolls", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"low",
    veg:["cucumber","carrot"], grain:["rice"], pulse:[] },
  { n:"Veg Spring Rolls (Baked)", slot:"dinner", cuisine:"Asian", dairy:"none", protein:"low",
    veg:["cabbage","carrot","bell pepper"], grain:["wheat"], pulse:[] },
  // -- Mexican additions --
  { n:"Veg Fajitas", slot:"dinner", cuisine:"Mexican", dairy:"light", protein:"low",
    veg:["bell pepper","onion"], grain:["tortilla"], pulse:[] },
  { n:"Enchiladas (Baked)", slot:"dinner", cuisine:"Mexican", dairy:"heavy", protein:"med",
    veg:["bell pepper","onion","tomato"], grain:["tortilla"], pulse:[] },
  { n:"Black Bean Soup + Toast", slot:"dinner", cuisine:"Mexican", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:["bread"], pulse:[] },
  { n:"Mexican Rice Bowl", slot:"dinner", cuisine:"Mexican", dairy:"light", protein:"med",
    veg:["bell pepper","onion","tomato"], grain:["rice"], pulse:[] },
  // -- Italian additions --
  { n:"Veg Lasagna (Whole Wheat)", slot:"dinner", cuisine:"Italian", dairy:"heavy", protein:"med",
    veg:["spinach","mushroom","tomato"], grain:["wheat"], pulse:[] },
  { n:"Eggplant Parmigiana (Baked)", slot:"dinner", cuisine:"Italian", dairy:"heavy", protein:"med",
    veg:["eggplant","tomato"], grain:[], pulse:[] },
  { n:"Minestrone Soup + Toast", slot:"dinner", cuisine:"Italian", dairy:"none", protein:"med",
    veg:["carrot","tomato"], grain:["bread","pasta"], pulse:[] },
  // -- Continental additions --
  { n:"Falafel + Hummus + Pita", slot:"dinner", cuisine:"Continental", dairy:"none", protein:"high",
    veg:[], grain:["wheat"], pulse:["chickpea"], soak:true },
  { n:"Mediterranean Bowl", slot:"dinner", cuisine:"Continental", dairy:"light", protein:"high",
    veg:["cucumber","tomato","bell pepper"], grain:["quinoa"], pulse:["chickpea"] },
  { n:"Tabouleh + Pita", slot:"dinner", cuisine:"Continental", dairy:"none", protein:"med",
    veg:["tomato","cucumber"], grain:["wheat"], pulse:[] },
  { n:"Stuffed Zucchini (Baked)", slot:"dinner", cuisine:"Continental", dairy:"light", protein:"low",
    veg:["zucchini","bell pepper"], grain:["rice"], pulse:[] },

  /* ============================================================
     Additions from external recipe blogs
     ============================================================ */

  // -- From The Chef and Her Kitchen (Prathibha, Andhra/Karnataka veg)
  { n:"Ven Pongal (Ghee Pongal)", slot:"breakfast", cuisine:"Indian", dairy:"light", protein:"med",
    veg:[], grain:["rice"], pulse:["moong dal"], src:"chefandherkitchen" },
  { n:"Davanagere Benne Dosa", slot:"breakfast", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["potato","onion"], grain:["rice"], pulse:["urad"], soak:true, src:"chefandherkitchen" },
  { n:"Sagu Masala Dosa", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["carrot","beans","peas","potato"], grain:["rice"], pulse:["urad"], soak:true, src:"chefandherkitchen" },
  { n:"Erra Kaaram Dosa (Rayalaseema)", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["onion"], grain:["rice"], pulse:["urad"], soak:true, src:"chefandherkitchen" },
  { n:"Kharada Eerulli Dosa", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["onion"], grain:["rice"], pulse:["urad","chana dal"], soak:true, src:"chefandherkitchen" },
  { n:"Gongura Pappu + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["gongura"], grain:["rice"], pulse:["toor dal"], src:"chefandherkitchen" },
  { n:"Gongura Pacchadi + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["gongura"], grain:["rice"], pulse:[], src:"chefandherkitchen" },
  { n:"Chamadumpa Vepudu (Arbi Roast) + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["arbi"], grain:["rice"], pulse:[], src:"chefandherkitchen" },
  { n:"Arbi Salan + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["arbi","tomato"], grain:["wheat"], pulse:[], src:"chefandherkitchen" },
  { n:"Drumstick Tomato Curry + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["drumstick","tomato"], grain:["rice"], pulse:[], src:"chefandherkitchen" },
  { n:"Andhra Potato Kurma + Roti", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["potato","onion"], grain:["wheat"], pulse:[], src:"chefandherkitchen" },
  { n:"Holige Saaru (Toor Dal Rasam) + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["tomato"], grain:["rice"], pulse:["toor dal"], src:"chefandherkitchen" },
  { n:"Whole Green Moong (Hara Moong) + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"high",
    veg:["onion","tomato"], grain:["wheat"], pulse:["moong dal"], src:"chefandherkitchen" },
  { n:"Sambar Sadam (Kadambam Rice)", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"high",
    veg:["carrot","beans","drumstick"], grain:["rice"], pulse:["toor dal"], src:"chefandherkitchen" },
  { n:"Pacchi Pulusu + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion","tomato"], grain:["rice"], pulse:[], src:"chefandherkitchen" },
  { n:"Stuffed Karela + Roti", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["karela","onion"], grain:["wheat"], pulse:["besan"], src:"chefandherkitchen" },
  { n:"Tomato Gotsu + Dosa", slot:"dinner", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["onion","tomato"], grain:["rice"], pulse:["moong dal","urad"], soak:true, src:"chefandherkitchen" },

  // -- From Hebbar's Kitchen (Archana, modern South Indian + pan-Indian veg)
  { n:"Khara Bath (Rava Masala Bath)", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["onion","peas","carrot","tomato"], grain:["rava"], pulse:[], src:"hebbarskitchen" },
  { n:"Tiffin Sambar + Idli", slot:"breakfast", cuisine:"Indian", dairy:"none", protein:"med",
    veg:["carrot","beans","drumstick"], grain:["rice"], pulse:["toor dal","urad"], soak:true, src:"hebbarskitchen" },
  { n:"Badanekayi Palya + Rice", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["eggplant"], grain:["rice"], pulse:[], src:"hebbarskitchen" },
  { n:"Rice Bath (Karnataka Veg Bath)", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["carrot","beans","peas"], grain:["rice"], pulse:[], src:"hebbarskitchen" },
  { n:"Tomato Bath", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"low",
    veg:["tomato","onion"], grain:["rice"], pulse:[], src:"hebbarskitchen" },
  { n:"Vangi Bath (Brinjal Rice)", slot:"lunch", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["eggplant"], grain:["rice"], pulse:[], src:"hebbarskitchen" },
  { n:"Masale Bhat (Maharashtrian)", slot:"lunch", cuisine:"Indian", dairy:"light", protein:"med",
    veg:["carrot","peas","potato","eggplant"], grain:["rice"], pulse:[], src:"hebbarskitchen" },
  { n:"Paneer Pulao", slot:"lunch", cuisine:"Indian", dairy:"heavy", protein:"high",
    veg:["onion","peas"], grain:["rice"], pulse:["paneer"], src:"hebbarskitchen" },
  { n:"Dahi Puri", slot:"snack", cuisine:"Indian", dairy:"heavy", protein:"low",
    veg:["potato","onion","tomato"], grain:[], pulse:[], src:"hebbarskitchen" },
  { n:"Aloo Matar Chaat (Delhi)", slot:"snack", cuisine:"Indian", dairy:"none", protein:"low",
    veg:["potato","peas","onion","tomato"], grain:[], pulse:[], src:"hebbarskitchen" },
];

const SLOTS = [
  { key:"breakfast", label:"Breakfast" },
  { key:"tiffin",    label:"Tiffin Box" },
  { key:"lunch",     label:"Lunch" },
  { key:"snack",     label:"Snack" },
  { key:"dinner",    label:"Dinner" },
];

// Expose to window for the UI shell
Object.assign(window, { VEG_OPTIONS, GRAIN_OPTIONS, PULSE_OPTIONS, MENU, SLOTS });
